// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/DeviceList.tsx": () => import("../components/mockups/DeviceList.tsx"),
  "./components/mockups/LiveMap.tsx": () => import("../components/mockups/LiveMap.tsx"),
  "./components/mockups/StatusComponents.tsx": () => import("../components/mockups/StatusComponents.tsx")
};
